### ISSUE TITLE
Console URL - west isn't working

### ISSUE THREAD

**Issue by openinsurer** [gopinaath/hide-aws-user-id-account-id#2]
AWS URL can be from alternate regions, like the one below:

https://us-west-2.console.aws.amazon.com/console/home?region=us-west-2#

AWS Account details are showing up when console URLs are different from the standard  (.https://console.aws.amazon.com/*/*)

**Comment by sysdevoperations** [comment]
PR submitted to resolve this issue:
https://github.com/gopinaath/hide-aws-user-id-account-id/pull/3

**Comment by gopinaath** [comment]
fixed by PR.
